#!/usr/bin/env bash
TEST_PROJECT=${1:-'env_packages'}
PROJECT_PATH='./test_projects/'$TEST_PROJECT'/'
echo $PYTHONPATH
export PYTHONPATH=${PYTHONPATH}:$PROJECT_PATH:.
echo $PYTHONPATH
python $PROJECT_PATH"manage.py" test serene
